# Azure Pipelines configuration
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '11.x'

# Test
- script: |
    npm i
    npm run test
  displayName: 'Test by mocha'
