# Azure Pipelines configuration
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '14.x'

# Test
- script: |
    npm i
    npm test
  displayName: 'Test'
