name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run tests
        run: |
          npm i
          npm test
